name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
      inputs:
        tag_name:
          description: 'Tag name for the release'
          required: true
          default: ''
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3
      
    # Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
   
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Build APK
    - uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Sign APK
    - name: Sign APK
      id: sign_release_apk
      uses: ilharp/sign-android-release@v1
      with:
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        buildToolsVersion: 34.0.0

    # Upload Release
    - name: Upload APK to Release
      uses: termux/upload-release-action@v4.2.0
      with:
        asset_name: app-release-${{ github.event.inputs.tag_name || github.ref_name }}.apk
        file: ${{ steps.sign_release_apk.outputs.signedFile }}
        repo_token: ${{ secrets.TOKEN }}
        tag: ${{ github.event.inputs.tag_name || github.ref_name }}
        overwrite: true
        body: |
          New release automatically generated by GitHub Actions.
        checksums: sha256
        checksums_file_name: app-release-${{ github.event.inputs.tag_name || github.ref_name }}.%algo%

    # - name: Upload Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     token: ${{secrets.TOKEN }}
    #     body: |
    #       New release automatically generated by GitHub Actions.
    #     files: app/build/outputs/apk/release/*.apk
    
    # 完成
    - run: echo "🍏 job's status is ${{ job.status }}."
